# Generated by Django 4.2.5 on 2023-09-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MoviesDB',
        ),
    ]
